# Generated by Django 5.2.9 on 2026-03-09 05:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_tenant_isolation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='organization_id',
        ),
        migrations.CreateModel(
            name='GlobalUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('tenant_user_id', models.IntegerField()),
                ('status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_users', to='accounts.organization')),
            ],
            options={
                'db_table': 'global_users',
                'indexes': [models.Index(fields=['email', 'organization'], name='global_user_email_3d8319_idx'), models.Index(fields=['tenant_user_id', 'organization'], name='global_user_tenant__3cbe2e_idx')],
                'unique_together': {('email', 'organization')},
            },
        ),
    ]
