# Generated by Django 5.2.9 on 2026-03-09 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_organization_id_globaluser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization_id',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
