# Generated by Django 5.2.11 on 2026-02-08 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='externaldatasource',
            name='connection_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='externaldatasource',
            name='connection_status',
            field=models.CharField(default='untested', max_length=20),
        ),
        migrations.AddField(
            model_name='externaldatasource',
            name='connection_string',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='externaldatasource',
            name='last_connection_test',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='externaldatasource',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='externaldatasource',
            name='password_encrypted',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='externaldatasource',
            name='ssl_cert_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='externaldatasource',
            name='ssl_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='externaldatasource',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='externaldatasource',
            name='credentials_ref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='externaldatasource',
            name='host',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='externaldatasource',
            name='port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='externaldatasource',
            name='type',
            field=models.CharField(choices=[('sqlite', 'SQLite'), ('postgres', 'PostgreSQL'), ('mysql', 'MySQL'), ('mariadb', 'MariaDB'), ('mongodb', 'MongoDB'), ('sqlserver', 'Microsoft SQL Server'), ('oracle', 'Oracle Database'), ('redis', 'Redis')], default='sqlite', max_length=20),
        ),
    ]
