# Generated by Django 5.0.3 on 2026-05-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_enhanced_data_sources'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='user',
        ),
        migrations.AddField(
            model_name='feedback',
            name='user_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='feedback',
            name='user_id',
            field=models.IntegerField(db_index=True, default=0),
            preserve_default=False,
        ),
    ]
