# Generated by Django 5.2.9 on 2026-03-03 20:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_organization_plan'),
        ('tickets', '0003_ticketwatcher_alter_tickethistory_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['organization', 'sla_resolution_deadline'], name='idx_ticket_org_sla_deadline'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['organization', 'due_date'], name='idx_ticket_org_due_date'),
        ),
    ]
