# Generated by Django 5.0.3 on 2026-05-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_remove_auditlog_audit_logs_user_id_fbfd51_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ticket_sequence',
            field=models.PositiveIntegerField(default=0, help_text='Atomic counter for generating unique ticket IDs'),
        ),
    ]
